modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
#updateJSONURL="http://myurl.me/"
#displayURL="http://example.com/"
logoFile = "assets/moreharnesses/icon.png"
#credits="Thanks for this example mod goes to Java"
authors = "Pitan"
description = '''
Adds new harnesses (Iron, Gold, ...) for the Happy Ghast!
'''

[[dependencies.${mod_id}]]
modId = "neoforge"
mandatory = true
versionRange = "[20,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21.6,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "mcpitanlib"
mandatory = true
versionRange = "[3.3.0,)"
ordering = "BEFORE"
side = "BOTH"

[[mixins]]
config = "moreharnesses-common.mixins.json"

[[mixins]]
config = "moreharnesses.mixins.json"
